version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-postgres:
    executor:
      name: solidusio_extensions/postgres
      ruby_version: '3.0'
    steps:
      - checkout
      - solidusio_extensions/dependencies
      - run:
          name: "Run specs on the legacy frontend with postgres"
          command: export FRONTEND=solidus_frontend
      - solidusio_extensions/test-branch:
          branch: v3.3
          rails_version: '~> 7.0'
      - solidusio_extensions/store-test-results
  run-specs-with-mysql:
    executor:
      name: solidusio_extensions/mysql
      ruby_version: '3.0'
    steps:
      - checkout
      - solidusio_extensions/dependencies
      - run:
          name: "Run specs on the legacy frontend with mysql"
          command: export FRONTEND=solidus_frontend
      - solidusio_extensions/test-branch:
          branch: v3.3
          rails_version: '~> 7.0'
      - solidusio_extensions/store-test-results
  lint-code:
    executor:
      name: solidusio_extensions/sqlite-memory
      ruby_version: '3.0'
    steps:
      - solidusio_extensions/lint-code

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
      - lint-code

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
